services:
  nginx-jackeline:
    image: nginx:latest
    container_name: nginx-web-jackeline
    ports:
      - "86:80"
    volumes: 
      - ../web:/usr/share/nginx/html:ro
    restart: unless-stopped